const PRODUCT_CATEGORIES = {
    electronics: [
        "LED TVs",
        "Smart TVs",
        "Home Theatre Systems",
        "Soundbars",
        "Amplifiers",
        "Speakers",
        "PA Systems",
        "CCTV Cameras",
        "DVR / NVR Systems",
        "Laptops",
        "Desktops",
        "Monitors",
        "Printers",
        "Scanners",
        "Projectors",
        "UPS Systems",
        "Inverters",
        "Stabilizers",
        "Voltage Regulators",
        "SMPS",
        "Power Supply Units",
        "Control Panels",
        "Hard Disks",
        "SSDs",
        "Pen Drives",
        "Memory Cards",
        "External Storage",
        "Biometric Devices",
        "Access Control Systems",
        "Attendance Machines",
        "Intercom Systems"
    ],
    electrical: [
        "Electrical Wires",
        "Power Cables",
        "Armoured Cables",
        "Flexible Cables",
        "Control Cables",
        "Switches",
        "Switch Boards",
        "Sockets",
        "Plug Tops",
        "MCB",
        "RCCB",
        "ELCB",
        "Fuse Units",
        "LED Bulbs",
        "Tube Lights",
        "Panel Lights",
        "Street Lights",
        "Flood Lights",
        "Decorative Lights",
        "Ceiling Fans",
        "Exhaust Fans",
        "Table Fans",
        "Coolers",
        "Heaters",
        "Geysers",
        "Distribution Boards",
        "Junction Boxes",
        "Control Panels",
        "Meter Boards",
        "Holders",
        "Regulators",
        "Conduits",
        "PVC Pipes",
        "Cable Trays",
        "Cable Ties",
        "Insulation Tape",
        "Multimeter",
        "Tester",
        "Electric Drill",
        "Soldering Iron",
        "Screwdriver Set"
    ]
};

export default PRODUCT_CATEGORIES;
